// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: car.proto

package proto;

public interface CarOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Car)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string nome = 2;</code>
   */
  java.lang.String getNome();
  /**
   * <code>string nome = 2;</code>
   */
  com.google.protobuf.ByteString
      getNomeBytes();

  /**
   * <code>string marca = 3;</code>
   */
  java.lang.String getMarca();
  /**
   * <code>string marca = 3;</code>
   */
  com.google.protobuf.ByteString
      getMarcaBytes();

  /**
   * <code>int32 anoFabricacao = 4;</code>
   */
  int getAnoFabricacao();

  /**
   * <code>int32 anoModelo = 5;</code>
   */
  int getAnoModelo();

  /**
   * <code>double preco = 6;</code>
   */
  double getPreco();
}
