// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: car.proto

package proto;

public interface CreateCarRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.CreateCarRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nome = 1;</code>
   */
  java.lang.String getNome();
  /**
   * <code>string nome = 1;</code>
   */
  com.google.protobuf.ByteString
      getNomeBytes();

  /**
   * <code>string marca = 2;</code>
   */
  java.lang.String getMarca();
  /**
   * <code>string marca = 2;</code>
   */
  com.google.protobuf.ByteString
      getMarcaBytes();

  /**
   * <code>int32 anoFabricacao = 3;</code>
   */
  int getAnoFabricacao();

  /**
   * <code>int32 anoModelo = 4;</code>
   */
  int getAnoModelo();

  /**
   * <code>double preco = 5;</code>
   */
  double getPreco();
}
