// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: car.proto

package proto;

public interface GetAllResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetAllResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.Car cars = 1;</code>
   */
  java.util.List<proto.Car> 
      getCarsList();
  /**
   * <code>repeated .proto.Car cars = 1;</code>
   */
  proto.Car getCars(int index);
  /**
   * <code>repeated .proto.Car cars = 1;</code>
   */
  int getCarsCount();
  /**
   * <code>repeated .proto.Car cars = 1;</code>
   */
  java.util.List<? extends proto.CarOrBuilder> 
      getCarsOrBuilderList();
  /**
   * <code>repeated .proto.Car cars = 1;</code>
   */
  proto.CarOrBuilder getCarsOrBuilder(
      int index);
}
