// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: car.proto

package proto;

public interface GetAllRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetAllRequest)
    com.google.protobuf.MessageOrBuilder {
}
